services:
    consumers-db:
        image: mysql:8.4
        environment:
            MYSQL_DATABASE: ${DB}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ../services/ConsumersDb/Configuration/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
            - ../services/ConsumersDb/Configuration/init:/docker-entrypoint-initdb.d:ro
            - ../services/ConsumersDb/Data:/var/lib/mysql
        healthcheck:
            test: mysqladmin ping -h localhost -uroot --password=${DB_ROOT_PASSWORD}
            start_period: 10s
            interval: 5s
            timeout: 5s
            retries: 10
        restart: unless-stopped
        ports:
            - "23308:3306"

    providers-db:
        image: mysql:8.4
        environment:
            MYSQL_DATABASE: ${DB}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ../services/ProvidersDb/Configuration/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
            - ../services/ProvidersDb/Configuration/init:/docker-entrypoint-initdb.d:ro
            - ../services/ProvidersDb/Data:/var/lib/mysql
        healthcheck:
            test: mysqladmin ping -h localhost -uroot --password=${DB_ROOT_PASSWORD}
            start_period: 10s
            interval: 5s
            timeout: 5s
            retries: 10
        restart: unless-stopped
        ports:
            - "23309:3306"

    contracts-db:
        image: mysql:8.4
        environment:
            MYSQL_DATABASE: ${DB}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ../services/ContractsDb/Configuration/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
            - ../services/ContractsDb/Configuration/init:/docker-entrypoint-initdb.d:ro
            - ../services/ContractsDb/Data:/var/lib/mysql
        healthcheck:
            test: mysqladmin ping -h localhost -uroot --password=${DB_ROOT_PASSWORD}
            start_period: 10s
            interval: 5s
            timeout: 5s
            retries: 10
        restart: unless-stopped
        ports:
            - "23310:3306"

    messaging-bus:
        image: rabbitmq:management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_USER_PASSWORD}
        healthcheck:
            test: rabbitmqctl node_health_check
            start_period: 10s
            interval: 5s
            timeout: 5s
            retries: 10
        restart: unless-stopped
        volumes:
          - ../services/MessagingBus/Data:/var/lib/rabbitmq
          - ../services/MessagingBus/Logs:/var/log/rabbitmq
        ports:
            - "5425:5672"
            - "15425:15672"
