services:
    consumers-db:
        image: mysql:8.4
        environment:
            MYSQL_DATABASE: ${DB}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ../services/ConsumersDb/Configuration/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
            - ../services/ConsumersDb/Configuration/init:/docker-entrypoint-initdb.d:ro
            - ../services/ConsumersDb/Data:/var/lib/mysql
        healthcheck:
            test: mysqladmin ping -h localhost -uroot --password=${DB_ROOT_PASSWORD}
            start_period: 10s
            interval: 5s
            timeout: 5s
            retries: 10
        restart: unless-stopped
        ports:
            - "23308:3306"
        networks:
            - intranet

networks:
    intranet:
